sudo: false

notifications:
  email: false

language: go

go:
  - 1.6

addons:
  postgresql: "9.4"

services:

env: GOARCH=amd64 TEST_HOST=127.0.0.1

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db
  - cd $GOPATH/src/upper.io/db
  - go get -v -t -d upper.io/db/postgresql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/db

script:
  - cd $GOPATH/src/upper.io/db
  - BENCHTIME=2s make test bench -C $GOPATH/src/upper.io/db/postgresql
